### ISSUE TITLE
500 error when viewing trend/terms/stats - NoMethodError - undefined method `<=>' for #<Hash:0x7f84c8c96770>

### ISSUE THREAD

**Issue by koddsson** [rashidkpc/kibana2#238]
I seem to be getting a 500 server error like issue #123 but with a different error.

Score seems to work though.

```
NoMethodError - undefined method `<=>' for #<Hash:0x7f84c8c96770>:
    ./lib/kelastic.rb:134:in `sort_by'
    ./lib/kelastic.rb:134:in `collect_item_attributes'
    ./lib/kelastic.rb:127:in `field_type'
    kibana.rb:204:in `GET /api/analyze/:field/mean/:hash'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1264:in `call'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1264
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `[]'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `route!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:851:in `route_eval'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `route!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:872:in `process_route'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in `catch'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in `process_route'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:834:in `route!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in `each'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in `route!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:936:in `dispatch!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `call!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `catch'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `call!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:755:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in `context'
    /usr/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/logger.rb:15:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/commonlogger.rb:20:in `call_without_check'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:136:in `call'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:129:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/head.rb:9:in `call'
    /usr/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in `call'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/showexceptions.rb:21:in `call'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:99:in `call'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1389:in `call'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1471:in `synchronize'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1389:in `call'
    /usr/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:81:in `pre_process'
    /usr/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:79:in `catch'
    /usr/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:79:in `pre_process'
    /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1037:in `call'
    /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1037:in `spawn_threadpool'
    /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1033:in `initialize'
    /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1033:in `new'
    /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1033:in `spawn_threadpool'
    /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:1023:in `defer'
    /usr/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:51:in `process'
    /usr/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/connection.rb:39:in `receive_data'
    /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run_machine'
    /usr/lib/ruby/gems/1.8/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    /usr/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/backends/base.rb:63:in `start'
    /usr/lib/ruby/gems/1.8/gems/thin-1.5.0/lib/thin/server.rb:159:in `start'
    /usr/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/handler/thin.rb:13:in `run'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1350:in `run!'
    /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/main.rb:25
    kibana.rb:310
```

**Comment by koddsson** [comment]
I updated ES to 0.20.2, logstash to 1.1.9 and kibana to the git version and that solved my issue.
