### ISSUE TITLE
statistics receive 500 error

### ISSUE THREAD

**Issue by jerryz1982** [rashidkpc/kibana2#337]
My setup is logstash1.1.9 shipper (log file) ->redis->logstash1.1.9 indexer->elasticsearch0.20.6->kibana (git version today 04.15.2013) . Everything else works except for stats with 500 error.
Someone please take a look at this. Thanks!

NoMethodError - undefined method `<=>' for #<Hash:0x7faa5fba2168>:
 /var/www/kibana/lib/kelastic.rb:136:in`sort_by'
 /var/www/kibana/lib/kelastic.rb:136:in `collect_item_attributes'
 /var/www/kibana/lib/kelastic.rb:129:in`field_type'
 /var/www/kibana/lib/kibana-app.rb:205:in `GET /api/analyze/:field/mean/:hash'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1151:in`call'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1151:in `compile!'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:724:in`instance_eval'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:724:in `route_eval'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:708:in`route!'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:758:in `process_route'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:755:in`catch'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:755:in `process_route'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:707:in`route!'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:706:in `each'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:706:in`route!'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:843:in `dispatch!'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:644:in`call!'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:808:in `instance_eval'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:808:in`invoke'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:808:in `catch'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:808:in`invoke'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:644:in `call!'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:629:in`call'
 /usr/lib/ruby/vendor_ruby/rack/session/abstract/id.rb:195:in `context'
 /usr/lib/ruby/vendor_ruby/rack/session/abstract/id.rb:190:in`call'
 /usr/lib/ruby/vendor_ruby/rack/head.rb:9:in `call'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1272:in`call'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1303:in `synchronize'
 /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1272:in`call'
 /usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:92:in `process_request'
 /usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:207:in`main_loop'
 /usr/lib/ruby/1.8/phusion_passenger/rack/application_spawner.rb:118:in `run'
 /usr/lib/ruby/1.8/phusion_passenger/rack/application_spawner.rb:65:in`spawn_application'
 /usr/lib/ruby/1.8/phusion_passenger/utils.rb:184:in `safe_fork'
 /usr/lib/ruby/1.8/phusion_passenger/rack/application_spawner.rb:58:in`spawn_application'
 /usr/lib/ruby/1.8/phusion_passenger/rack/application_spawner.rb:41:in `spawn_application'
 /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:159:in`spawn_application'
 /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
 /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in`**send**'
 /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
 /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in`start_synchronously'
 /usr/lib/phusion_passenger/passenger-spawn-server:61

**Comment by jerryz1982** [comment]
This exception only occur when graylog2 is also storing logs onto elasticsearch. If graylog is stopped and elasticsearch is cleared, making logstash as the only source, the stat for @message would display a warning that stat is for number only rather than 500 internal server error, which i think is reasonable.
