### ISSUE TITLE
Graph not getting loaded in Kibana

### ISSUE THREAD

**Issue by umarengasamy** [rashidkpc/kibana2#388]
Kibana doest load graph on the main page getting below error (Logstash is loading the graph , problem is only with kibana )  
Using Kibana-0.2.0 , ElasticSearch 0.20.5 and Logstash1.1.16. 

[2013-07-26 13:22:58,324][DEBUG][action.search.type       ] [Dragonwing] [logstash-2013.07.26][1], node[Xv_c3A93QBWwPyCOq3HCPA], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@1fe256b]
org.elasticsearch.search.query.QueryPhaseExecutionException: [logstash-2013.07.26][1]: query[ConstantScore(NotDeleted(cache(@timestamp:[1374738778000 TO 1374825178999])))],from[0],size[0]: Query Failed [Failed to execute main query]
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:182)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:242)
        at org.elasticsearch.search.action.SearchServiceTransportAction.sendExecuteQuery(SearchServiceTransportAction.java:141)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction.sendExecuteFirstPhase(TransportSearchQueryThenFetchAction.java:80)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.performFirstPhase(TransportSearchTypeAction.java:205)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.performFirstPhase(TransportSearchTypeAction.java:192)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$2.run(TransportSearchTypeAction.java:178)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.ArithmeticException: / by zero

**Comment by umarengasamy** [comment]
Is this related to time zone setting .?
Caused by: java.lang.ArithmeticException: / by zero
        at org.elasticsearch.common.joda.TimeZoneRounding$UTCIntervalTimeZoneRounding.calc(TimeZoneRounding.java:195)
        at org.elasticsearch.search.facet.datehistogram.CountDateHistogramFacetCollector$DateHistogramProc.onValue(CountDateHistogramFacetCollector.java:105)
        at org.elasticsearch.index.field.data.longs.SingleValueLongFieldData.forEachValueInDoc(SingleValueLongFieldData.java:105)
        at org.elasticsearch.search.facet.datehistogram.CountDateHistogramFacetCollector.doCollect(CountDateHistogramFacetCollector.java:80)
        at org.elasticsearch.search.facet.AbstractFacetCollector.collect(AbstractFacetCollector.java:89)
