### ISSUE TITLE
Stream doesn't work (always empty) and NoMethodError exception in the log

### ISSUE THREAD

**Issue by timbunce** [rashidkpc/kibana2#68]
Hi. I'm just trying out Kibana and it looks good. Thank you!

Sadly the streaming doesn't work for me. Whenever I click on stream I get a page with a pause button on a black header bar and below that the current query string. Then nothing.

In the log I can see an exception being thrown every few seconds. I've appended the exception trace below.

Stats: Kibana 269f9538 (latest), Ruby 1.8.7, ES 0.19.8. Our logstash indices are named logstash-%{@source}-%{+YYYY.MM}".

Tim.

```
NoMethodError - undefined method `[]' for nil:NilClass:
    kibana.rb:193:in `GET /api/stream/:hash/?:from?'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1264:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1264:in `compile!'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `[]'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `route!'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:851:in `route_eval'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `route!'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:872:in `process_route'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in `catch'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in `process_route'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:834:in `route!'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in `each'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in `route!'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:936:in `dispatch!'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `call!'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `catch'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `call!'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:755:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in `context'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/logger.rb:15:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/commonlogger.rb:20:in `call_without_check'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:136:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:129:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/head.rb:9:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/showexceptions.rb:21:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:99:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1389:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1471:in `synchronize'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1389:in `call'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/handler/webrick.rb:59:in `service'
    /usr/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
    /usr/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
    /usr/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
    /usr/lib/ruby/1.8/webrick/server.rb:162:in `start'
    /usr/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
    /usr/lib/ruby/1.8/webrick/server.rb:95:in `start'
    /usr/lib/ruby/1.8/webrick/server.rb:92:in `each'
    /usr/lib/ruby/1.8/webrick/server.rb:92:in `start'
    /usr/lib/ruby/1.8/webrick/server.rb:23:in `start'
    /usr/lib/ruby/1.8/webrick/server.rb:82:in `start'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/handler/webrick.rb:13:in `run'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/base.rb:1350:in `run!'
    /home/tim/trunk/nub/comp/logview/ruby/lib/ruby/gems/1.8/gems/sinatra-1.3.3/lib/sinatra/main.rb:25
    kibana.rb:260
 86.47.232.121 - - [10/Sep/2012:07:03:16 CDT] "GET /api/stream/eyJzZWFyY2giOiIgQHNvdXJjZTpcInRsc3ZjdGxcIiIsImZpZWxkcyI6WyJAbWVzc2FnZSJdLCJvZmZzZXQiOjAsInRpbWVmcmFtZSI6OTAwLCJncmFwaG1vZGUiOiJjb3VudCIsIm1vZGUiOiIiLCJhbmFseXplX2ZpZWxkIjoiIn0= HTTP/1.1" 500 5483
```

**Comment by rashidkpc** [comment]
This might be fixed, there was a bug in the current_index function that was affecting the stream

**Comment by timbunce** [comment]
That didn't help, sadly. I get the same strack trace.

Looking at the diff makes me wonder if the problem is related to our index names. We're using "logstash-%{@source}-%{+YYYY.MM}" so the current_index function will be guessing wrongly.

**Comment by rashidkpc** [comment]
Ah yeah, that seems likely, I'm guessing you have Smart_index = false set in KibanaConfig.rb? I missed adding the check for Smart_index to the current_index function. I just added it and committed it.

**Comment by timbunce** [comment]
That worked, thanks.

Though wouldn't it be better to move the "logstash-%Y.%m.%d" string itself into the config?

Now that elasticsearch 0.19.8+ supports [wildcards in indices](http://www.elasticsearch.org/blog/2012/07/02/0.19.8-released.html), if I could specify the strftime format string in the config I'd be able to use something like:

  Smart_index = "logstash-*-%Y.%m"

Seems like that would make 'smart index' _much_ smarter.

**Comment by rashidkpc** [comment]
recent pull from r_duran made smart indexing configurable
